// embed_assets.js
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const publicDir = path.join(__dirname, 'public');
const outputFilePath = path.join(__dirname, 'src', 'embedded_assets.js'); // Place it inside src

async function embedAssets() {
  try {
    console.log('Embedding static assets...');
    const htmlContent = await fs.readFile(path.join(publicDir, 'index.html'), 'utf8');
    const cssContent = await fs.readFile(path.join(publicDir, 'style.css'), 'utf8');
    const jsContent = await fs.readFile(path.join(publicDir, 'client.js'), 'utf8');

    // Base64 encode the content
    const encodedHtml = Buffer.from(htmlContent).toString('base64');
    const encodedCss = Buffer.from(cssContent).toString('base64');
    const encodedJs = Buffer.from(jsContent).toString('base64');

    const outputJs = `
// This file is auto-generated by embed_assets.js. Do not edit manually.
export const assets = {
  'index.html': '${encodedHtml}',
  'style.css': '${encodedCss}',
  'client.js': '${encodedJs}'
};
`;

    await fs.mkdir(path.dirname(outputFilePath), { recursive: true });
    await fs.writeFile(outputFilePath, outputJs);
    console.log('Successfully embedded assets into src/embedded_assets.js');
  } catch (error) {
    console.error('Error embedding assets:', error);
    process.exit(1);
  }
}

embedAssets();